name: Tests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install modules
      run: npm install
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3