name: Tests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.1
    - run: npm ci
    - run: npm test